// <auto-generated />
using System;
using AlbumList.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AlbumList.Migrations
{
    [DbContext(typeof(AlbumContext))]
    [Migration("20211207012824_Final")]
    partial class Final
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.4")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AlbumList.Models.ListensModel", b =>
                {
                    b.Property<int>("ListensModelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Album")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Artist")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Rating")
                        .IsRequired()
                        .HasColumnType("float");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ListensModelId");

                    b.ToTable("Listens");

                    b.HasData(
                        new
                        {
                            ListensModelId = 1,
                            Album = "Blonde",
                            Artist = "Frank Ocean",
                            Rating = 6.0,
                            Title = "Ivy"
                        },
                        new
                        {
                            ListensModelId = 2,
                            Album = "Selected Ambient Works Volume II",
                            Artist = "Aphex Twin",
                            Rating = 3.0,
                            Title = "#3"
                        },
                        new
                        {
                            ListensModelId = 3,
                            Album = "The Bends",
                            Artist = "Radiohead",
                            Rating = 9.0,
                            Title = "Fake Plastic Trees"
                        },
                        new
                        {
                            ListensModelId = 4,
                            Album = "Kickback",
                            Artist = "KanKan",
                            Rating = 5.0,
                            Title = "Kickback"
                        },
                        new
                        {
                            ListensModelId = 5,
                            Album = "After Me",
                            Artist = "SoFaygo",
                            Rating = 6.0,
                            Title = "Everyday"
                        },
                        new
                        {
                            ListensModelId = 6,
                            Album = "Let's Skip to the Wedding",
                            Artist = "Eyedress",
                            Rating = 1.0,
                            Title = "Kiss Me Like It's the First Time"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
